image: Visual Studio 2019

environment:
  matrix:

  - job_name: all projects

  - job_name: each CMakeLists.txt

for:

  -
    matrix:
      only:
        - job_name: all projects

    build_script:
    - cmd: cmake -H. -B_build
    - cmd: cmake --build _build
  -
    matrix:
      only:
        - job_name: each CMakeLists.txt

    build_script:
    - cmd: cmake formatter_lib/CMakeLists.txt -Bformatter_lib/_build -DCMAKE_CURRENT_SOURCE_DIR=$PWD
    - cmd: cmake --build formatter_lib/_build
    - cmd: cmake formatter_ex_lib/CMakeLists.txt -Bformatter_ex_lib/_build -DCMAKE_CURRENT_SOURCE_DIR=$PWD
    - cmd: cmake --build formatter_ex_lib/_build
    - cmd: cmake hello_world_application/CMakeLists.txt -Bhello_world_application/_build -DCMAKE_CURRENT_SOURCE_DIR=$PWD
    - cmd: cmake --build hello_world_application/_build
    - cmd: cmake solver_application/CMakeLists.txt -Bsolver_application/_build -DCMAKE_CURRENT_SOURCE_DIR=$PWD
    - cmd: cmake --build solver_application/_build
